#!/usr/bin/env python
import os, sys
import stat
from glob import glob

mode = stat.S_IRUSR|stat.S_IWUSR

allfn = glob("authorized_keys.*")
allfn.sort()
wantext = sys.argv[1:]
newallfn = list()
for fn in allfn:
    if len(wantext) > 0:
        for ext in wantext:
            if fn.endswith(ext):
                newallfn.append(fn)
                break
    else:
        newallfn.append(fn)
allfn = newallfn

fa = open("authorized_keys", 'w')
for fn in allfn:
    fa.write("# from %s\n" % fn)
    fa.write(open(fn).read())
    fa.write("\n")
    os.chmod(fn, mode)
fa.close()
os.chmod("authorized_keys", mode)
